#!/bin/sh
echo char version=\"`
if [ -e ./debian/changelog ]; then
	cat ./debian/changelog | head -1 | grep -Poe "[^\(]*(?=\))"
else
	#also removed from static rpm: cat ./ocompiler.spec | grep ^Version | grep -o "[^ ]*$"
	cat ./localtest
fi
`\" > ./version.oh
