on:
 workflow_dispatch:
  inputs:
   branch:
    description: "another branch"
env:
 #for gh and for upload
 GITHUB_TOKEN: ${{ secrets.PAT }}
jobs:
 takescreen:
  runs-on: ${{ matrix.os }}
  strategy:
   matrix:
    os: [ubuntu-22.04, ubuntu-24.04]
  steps:
   - uses: actions/checkout@master
   - name: Run a multi-line script
     run: |
      #proj
      name=`cat debian/changelog | head -1 | grep -o ^[^\ ]*`
      #get appimage artifact
      branch=${{ github.event.inputs.branch }}
      if [ -z "${branch}" ]; then
       branch=$(git rev-parse --abbrev-ref HEAD)
      fi
      id=$(gh run list --workflow=appimage.yml -b ${branch} | cut -f7 | head -1)
      repo_at_gh=`cat debian/control | grep "^Homepage" | grep -o "[^/]*$"`
      #
      url=`gh api -H "Accept: application/vnd.github.v3+json" /repos/colin-i/${repo_at_gh}/actions/runs/${id}/artifacts | jq ".artifacts[0].archive_download_url"`
      url=${url:1:-1}
      echo ${url}
      curl -L -H "Authorization: token ${{ secrets.PAT }}" ${url} --output a.zip
      unzip ./a.zip

      apt download libfuse2`if [ ${{ matrix.os }} = "ubuntu-24.04" ]; then echo -n t64; fi` #xvfb is already
      dpkg -x ./*.deb q

      test=$(LD_LIBRARY_PATH=$(pwd)/q/lib/x86_64-linux-gnu ./${name}.AppImage 0 2>&1 | head -1)
      if [ "${test}" != 'O Compiler - usage: o "filename" [[pref1 value1]...[prefN valueN]]' ]; then echo ${test}; exit 1; fi

      sudo apt install -y xterm imagemagick #imagemagick is on jammy, not on noble

      sudo Xvfb :99 -screen 0 1920x1080x8 &
      sleep 5
      export DISPLAY=:99
      LD_LIBRARY_PATH=`pwd`/q/lib/x86_64-linux-gnu xterm -hold -e "./${name}.AppImage 0;echo;./${name}.AppImage 1;echo;./${name}.AppImage 2;echo;./${name}.AppImage 3" &
      sleep 15
      import -window root -screen screenshot.png
   - name: upload artifact
     uses: actions/upload-artifact@master
     with:
      name: screenshot-${{ matrix.os }}
      path: screenshot.png
