
on:
 workflow_dispatch:

jobs:
 ubuildgen:
  runs-on: ubuntu-22.04
  steps:
   - name: Run a multi-line script
     run: |
      if [ -n "${{ env.init }}" ]; then
       exit 1
      fi
      #get up_url
      wget https://github.com/colin-i/test/releases/download/1.5/${{ env.proj }} -O 1.txt
      echo "up_url=`cat 1.txt`" >> $GITHUB_ENV
      if [ -z "${{ env.assetname }}" ]; then
       echo "assetname=${{ env.fname }}" >> $GITHUB_ENV
      fi
   - name: Upload Release Asset
     uses: actions/upload-release-asset@v1
     env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
     with:
      upload_url: ${{ env.up_url }}
      asset_path: ./${{ env.fname }}
      asset_name: ${{ env.assetname }}
      asset_content_type: ${{ env.mime }}
